function update_start_scene_config_audio_main_update_volume()
    update_SFX_VOLUME(audio_SFX_start_scene_confirm_1)
    update_SFX_VOLUME(audio_SFX_start_scene_confirm_2)
    update_SFX_VOLUME(audio_SFX_start_scene_confirm_3)
    update_SFX_VOLUME(audio_SFX_start_scene_confirm_4)
    update_SFX_VOLUME(audio_SFX_start_scene_exit_1)
    update_SFX_VOLUME(audio_SFX_start_scene_exit_2)
    update_SFX_VOLUME(audio_SFX_start_scene_up_1)
    update_SFX_VOLUME(audio_SFX_start_scene_up_2)
    update_SFX_VOLUME(audio_SFX_start_scene_down_1)
    update_SFX_VOLUME(audio_SFX_start_scene_down_2)
    update_SFX_VOLUME(audio_SFX_start_scene_left_1)
    update_SFX_VOLUME(audio_SFX_start_scene_left_2)
    update_SFX_VOLUME(audio_SFX_start_scene_right_1)
    update_SFX_VOLUME(audio_SFX_start_scene_right_2)
    update_SFX_VOLUME(audio_SFX_start_scene_blazblue_click_echo)
    update_SFX_VOLUME(audio_SFX_start_scene_scene_out)
    
    update_BGM_VOLUME(audio_BGM_start_scene_NOC_high)
    update_BGM_VOLUME(audio_BGM_start_scene_NOC_low)
end